lobby:
  world: "world"
  protection:
    chat: false
    damage: true
    drop: true
    pickup: true
    interact: true
messages:
  prefix: "&6&lPlayerRealms >>&r"
  lobbyprotection:
    chat: "%prefix% Chating is disabled in lobby"
    damage: "%prefix% Dealing damage is disabled in lobby"
    drop: "%prefix% Dropping items is disabled in lobby"
    interact: "%prefix% Intearacting is disabled in lobby"
  logs:
    reload:
      done: "%prefix% Plugin config reloaded"
    updateavaliable: "An update is avaliable, downoad it at %url%"
    execute:
      playeronly: "%prefix% Only player can execute this command"
  realms:
    creation:
      started: "%prefix% Realm creation has stared. May lag"
      done: "%prefix% Done. Use /realms to go to your realm"
    chat:
      deop: "[&8PLAYER&f] %player% %msg%"
      op: "[&4OP&f] %player% %msg%"
      creator: "[&cCREATOR&f] %player% %msg%"
    opening: "%prefix% Opening realm, please wait"
    deleted: "%prefix% Realm deleted"
  commands:
    rc:
      errors:
        realmonly: "%prefix% This command won't work outsite of realm"
        nopermission: "%prefix% Insufficent permission"
        noargs: "%prefix% Not enough arguments"
      noargs:
        header: "&e---------- &rHelp: Realm &e------------------------"
        description: "&7Below is a list of all Realm commands:"
        body: "&6/rc %command%: &r%description%"
      gamemode:
        set: "%prefix% Set own game mode to %gamemode% Mode"
        setother: "%prefix% Set %player%'s gamemode to %gamemode% Mode"
        error: "%prefix% %gamemode% is not proper game mode"
        check: "%prefix% Your gamemode is %gamemode%"
      op:
        creator: "%prefix% You cannot op realm creator"
        success: "%prefix% Made %player% a server operator"
      deop:
        creator: "%prefix% You cannot deop realm creator"
        success: "%prefix% Made %player% no longer a server operator"
      time:
        set: "%prefix% Set time to %time%"
        error: "%prefix% %time% is not proper time value"
        check: "%prefix% The time is %time%"
      difficulty:
        set: "%prefix% The difficulty has been set to %difficulty%"
        error: "%prefix% %difficulty% is not propper difficulty mode"
        check: "%prefix% The difficulty is %difficulty%"
      pvp:
        set: "%prefix% Set pvp mode to %pvp%"
        error: "%prefix% %pvp% is not proper pvp mode"
        check: "%prefix% Pvp mode is %pvp%"
      defaultgamemode:
        set: "%prefix% The default game mode is now %gamemode% Mode"
        error: "%prefix% %gamemode% is not proper game mode"
      close:
        success: "%prefix% Realm closed"
      clear:
        success: "%prefix% Cleared %player%'s inventory"
      weather:
        set: "%prefix% Set the weather to %weather%"
        error: "%prefix% %weather% is not proper weather"
    overworld:
      errors:
        alreadyinoverworld: "%prefix% &4&lYou are already in the overworld"
items:
  next:
    item: arrow
    name: "Next"
  close:
    item: barrier
    name: "Close"
  previous:
    item: arrow
    name: "Previous"
  admin:
    reload:
      item: compass
      name: "Reload config"
  realms:
    create:
      item: dark_oak_door
      name: "Create a realm"
    go:
      item: dark_oak_door
      name: "Go to your realm"
    gotolobby:
      item: compass
      name: "Go to lobby"
    visit:
      item: acacia_door
      name: "Visit a realm"
      tpitem: oak_sign
    manage:
      item: redstone_block
      name: "Manage realm settings"
      delete:
        item: tnt
        name: "Delete realm"
        lore: "Click here if you want to delete your realm"
      visibility:
        item: oak_sign
        name: "Change visibility"
        lore: "Current: &e%visibility%"
      close:
        item: barrier
        name: "Close realm"
      open:
        item: dark_oak_door
        name: "Open realm"
guis:
  realms:
    selector: "Realm menu - Selector"
    deop: "&8Realm menu - DEOP"
    op: "&4Realm menu - OP"
    creator: "&cRealm menu - Creator"
    manage: "&eRealm menu - Manage"
    visit: "Realm menu - Visit"
    admin: "PlayerRealms - Admin menu"
    teleport: "Realm menu - Teleport"