lobby:
  world: "world"
  protection:
    chat: false
    damage: true
    drop: true
    pickup: true
    interact: true
messages:
  prefix: "&6&lPlayerRealms >>&r"
  lobbyprotection:
    chat: "%prefix% Chating is disabled in lobby"
    damage: "%prefix% Dealing damage is disabled in lobby"
    drop: "%prefix% Dropping items is disabled in lobby"
    interact: "%prefix% Intearacting is disabled in lobby"
  logs:
    reload:
      done: "%prefix% Plugin config reloaded"
    execute:
      playeronly: "%prefix% Only player can execute this command"
  realms:
    creation:
      started: "%prefix% Realm creation has stared. May lag"
      done: "%prefix% Done. Use /realms to go to your realm"
    chat:
      deop: "[&8PLAYER&f] %player% %msg%"
      op: "[&4OP&f] %player% %msg%"
      creator: "[&cCREATOR&f] %player% %msg%"
    opening: "%prefix% Opening realm, please wait"
    renewed: "%prefix% Realm renewed"
    deleted: "%prefix% Realm deleted"
  commands:
    rc:
      errors:
        realmonly: "%prefix% This command won't work outsite of realm"
        nopermission: "%prefix% Insufficent permission"
      noargs:
        header: "&e---------- &rHelp: Realm &e----------"
        description: "&7Below is a list of all Realm commands:"
        body: "&6/rc %command%: &r%description%"
      gamemode:
        set: "%prefix% Set own game mode to %gamemode% Mode"
        error: "%prefix% %gamemode% is not proper game mode"
      op:
        creator: "%prefix% You cannot op realm creator"
        success: "%prefix% Made %target% a server operator"
      deop:
        creator: "%prefix% You cannot deop realm creator"
        success: "%prefix% Made %target% no longer a server operator"
      time:
        set: "%prefix% Set time to %time%"
        error: "%prefix% %time% is not proper time value"
      difficulty:
        set: "%prefix% The difficulcty has been set to %difficulty%"
        error: "%prefix% %difficulty% is not propper difficulty mode"
      pvp:
        set: "%prefix% Set pvp mode to %mode%"
        error: "%prefix% %mode% is not proper pvp mode"
      defaultgamemode:
        set: "%prefix% The default game mode is now %gamemode% Mode"
        error: "%prefix% %gamemode% is not proper game mode"
      close:
        success: "%prefix% Realm closed"
      clear:
        success: "%prefix% Cleared %target%'s inventory"
      weather:
        set: "%prefix% Set the weather to %weather%"
        error: "%prefix% %weather% is not proper weather"
items:
  next:
    item: arrow
    name: "Next"
  close:
    item: barrier
    name: "Close"
  previous:
    item: arrow
    name: "Previous"
  realms:
    create:
      item: dark_oak_door
      name: "Create a realm"
    go:
      item: dark_oak_door
      name: "Go to your realm"
    gotolobby:
      item: compass
      name: "Go to lobby"
    visit:
      item: acacia_door
      name: "Visit a realm"
      tpitem: oak_sign
    manage:
      item: redstone_block
      name: "Manage realm settings"
      delete:
        item: tnt
        name: "Delete realm"
        lore: "Click here if you want to delete your realm"
      visibility:
        item: oak_sign
        name: "Change visibility"
        lore: "Current: &e%visibility%"
guis:
  realms:
    selector: "Realm menu - Selector"
    deop: "Realm menu - DEOP"
    op: "Realm menu - OP"
    creator: "Realm menu - Creator"
    manage: "Realm menu - Manage"
    visit: "Ream menu - Visit"