name: PlayerRealms
main: cyber.playerrealms.Main
description: Free realms plugin
version: 1.1
author: Cyber
depend: [ Multiverse-Core, PerWorldServer, PerWorldInventory ]
api-version: 1.16
commands:
  realms:
      description: Opens plugin player ui.
      usage: /<command>
      permission: playerrealms.realms
  rc:
    description: Allows you to execute commands on relam.
    usage: /<command> <subcommand> [arguments...]
    permission: playerrealms.realms
  pra:
    description: Opens plugin admin ui.
    usage: /<command>
    permission: playerrealms.admin
permissions:
  playerrealms.realms:
      description: Allows usage of plugin player commands
      default: true
  playerrealms.admin:
    description: Allows usage of plugin admin commands
    default: op