name: PlayerRealms
main: cyber.playerrealms.Main
description: Free realms plugin
version: 1.0
author: Cyber
depend: [ Multiverse-Core, PerWorldServer, PerWorldInventory ]
api-version: 1.16
commands:
  realms:
      description: Open realms management gui.
      usage: /<command>
      permission: playerrealms.realms
  rc:
    description: Realm commands.
    usage: /<command> <subcommand> [arguments...]
    permission: playerrealms.realms
  pra:
    description: PlayerRealms admin command.
    usage: /<command>
    permission: playerrealms.admin
permissions:
  playerrealms.realms:
      description: Allows usage of plugin player commands
      default: true
  playerrealms.admin:
    description: Allows usage of plugin admin commands
    default: op